In [2]:
import numpy as np

In [10]:
arr1= np.array ([11,22,33,44,55]) #Create an empty array
arr1.dtype
arr2= np.array(['frmale','male','female'])
arr2.dtype

dtype('<U6')

In [21]:
l1=[11,22,33,44,55,66]
l2=[22,33,44,55,66,77]
array1 = np.array((l1,l2))
type(array1)
#type of array

numpy.ndarray

In [23]:
#Dimention of array
array1.ndim

2

In [31]:
#Size of array ---->number of item present in the array
array1.size

12

In [30]:
#Shape of array ---->number of rows and colums
array1.shape

(2, 6)

In [28]:
#array can be of n diamenstions
matrix=[[11,22,33],[44,55,66],[77,88,99]]
matrix_array= np.array(matrix)
matrix_array

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [57]:
#array can be of n diamenstions
matrix=[[[11,22,33],[44,55,66],[77,88,99]]]
matrix_array= np.array(matrix)
matrix_array.ndim

3

In [58]:
print('The Diamenstion of array',matrix_array.ndim)

The Diamenstion of array 3


In [59]:
#Rebuild functions
#1.Reshape Function
matrix_array.shape

(1, 3, 3)

In [60]:
matrix_array.reshape(-1)

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [77]:
matrix_array.reshape(1,3,3)

array([[[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [69]:
matrix_array.reshape(-2)

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [78]:
#Arange Function(Start,Step,Stop)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
#step
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [81]:
#Zeros and once

In [88]:
#Generate array of zero & once
np.zeros(2)

array([0., 0.])

In [95]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [96]:
np.ones(2)

array([1., 1.])

In [98]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [100]:
#Linspace
#Return every spaced number over a specif interval
np.linspace(1,10) #it check defualt 50 observation

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [105]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [106]:
#Eye
#Create an identity matrix

In [111]:
np.eye(4) #Generate 2d array of (5,5)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [113]:
#Broadcasting in an array

In [112]:
array1=np.array([1,2,3,4,5,6])
array1*3

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
#Randmon number generation with rand

In [115]:
np.random.rand()  #-----> it always generate the new numbers in between 0 to 1

0.32322164500778383

In [117]:
np.random.rand(5) #----> rand gives random 5 value in between 0 to 1

array([0.81019655, 0.70543593, 0.09569001, 0.14512654, 0.62285597])

In [121]:
np.random.rand(3,2,4)

array([[[0.38492051, 0.65259363, 0.04194602, 0.18907941],
        [0.75851478, 0.76250522, 0.07904322, 0.44213794]],

       [[0.10156838, 0.35219932, 0.26093691, 0.76911895],
        [0.26528691, 0.04393819, 0.96295418, 0.55420493]],

       [[0.59313877, 0.01669608, 0.27974867, 0.67526196],
        [0.4003777 , 0.37637146, 0.92529617, 0.80212755]]])

In [122]:
#Random number generation with randn

In [124]:
np.random.randn() #----->> it generate values between -3 to 3

-0.7149988893152232

In [125]:
np.random.randn(3,2,4)

array([[[-0.42412277, -0.11386499,  1.07800284,  0.81232088],
        [-0.22641386,  1.0578303 , -1.77453332, -1.67513404]],

       [[ 1.76358443,  0.95204643, -0.29707152,  0.9764834 ],
        [-1.2887199 ,  1.09658911,  1.08868954,  1.00653391]],

       [[ 0.87528994,  0.76174775, -0.05486592,  0.33864771],
        [-1.74538952, -0.06537292,  0.55490386, -0.40819332]]])

In [126]:
#Random number generation with randint

In [127]:
np.random.randint(1,100)

55

In [128]:
np.random.randint(1,100,5)

array([46, 35, 51, 67, 82], dtype=int32)

In [132]:
np.random.randint(1,100,2)

array([70, 99], dtype=int32)

In [138]:
#Using all three functions with your dob
np.random.rand(2,0,0,2,1,6,5) #----->> they show empty array bcoz 0 involved in your number

array([], shape=(2, 0, 0, 2, 1, 6, 5), dtype=float64)

In [139]:
np.random.randint(16,2002,5)

array([ 742,  671, 1095,  889, 1299], dtype=int32)

In [140]:
arr1=np.random.randint(16,2002,5)
arr1

array([1699, 1871,  570, 1973,  295], dtype=int32)

In [141]:
arr1.max()

np.int32(1973)

In [142]:
arr1.min()

np.int32(295)

In [143]:
arr1.argmax()

np.int64(3)

In [144]:
arr1.argmin()

np.int64(4)